# docker run --name mysql -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=groupay -p 3306:3306 -d mysql
# mvn clean install
# docker build -t groupay -f Dockerfile .
# docker stop mysql
# docker rm mysql
# docker compose up

version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: groupay
    ports:
      - 3306:3306
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -ppass"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  spring-app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/groupay
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass