# docker run --name mysql -e MYSQL_ROOT_PASSWORD=pass -e MYSQL_DATABASE=groupay -p 3306:3306 -d mysql
# mvn clean install
# docker build -t groupay -f Dockerfile .
# docker stop mysql
# docker rm mysql
# docker compose up

version: '3'
services:
  spring-app:
    build: .
    ports:
      - 8080:8080
    networks:
      - appnet
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/groupay
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      database:
        condition: service_healthy
  database:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: groupay
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p$$MYSQL_ROOT_PASSWORD","--protocol","tcp"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - 3306:3306
    networks:
      - appnet
    restart: always
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
networks:
  appnet: {}