# docker-compose up

version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: groupay
    ports:
      - 3306:3306
    restart: always